// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Employee.DAL;
using Employee.Models.Entities;

namespace Employee.DAL.DatabaseContext
{
    public partial class CDContext : DbContext
    {
        public CDContext()
        {
        }

        public CDContext(DbContextOptions<CDContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Donors> Donors { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Donors>(entity =>
            {
                entity.HasIndex(e => e.Email)
                    .HasName("UQ__Donors__A9D105349F7FEBE4")
                    .IsUnique();

                entity.Property(e => e.City)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.Country)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.MiddleName).IsUnicode(false);

                entity.Property(e => e.Password).IsRequired();

                entity.Property(e => e.Phone).IsUnicode(false);

                entity.Property(e => e.State)
                    .IsRequired()
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}